Form and function
nathen418/INFOST440-final-project pull request #7
Opened 2022-12-09 18:39 UTC by nathen418

- Updates styling across the entire site to be more consistent
- Updates and fixes the formatting of cards across the site
- Updates redirect locations to improve the user experience
- Hides the user list and changes password nav links until the user is logged in
- Attempts to make code formatting more consistent across files
- Starts the switch from links to buttons for actions

2022-12-09 23:03 UTC, Flakari requested changes
Overall things look good, just a simple fix is needed in createblogpost.php and it should be all set.

2022-12-09 23:03 UTC, Flakari commented on createblogpost.php
> +        echo "<script> window.location.assign('index.php'); </script>";
We can actually use `redirect_user()` here if we bring `include('header.php');` after the block started at line 7. Also I was getting a 'Warning: Undefined array key 0' error when the create post form has valid input. We can replace the current if check with `if (empty($errors))`.

2022-12-09 23:19 UTC, nathen418 commented on createblogpost.php
> +        echo "<script> window.location.assign('index.php'); </script>";
I'll get this in the morning, I get off work at 11:30 tonight😫

2022-12-11 00:19 UTC, Flakari approved these changes

2022-12-11 00:46 UTC, merged